settings:
  maxHeight: 80.0
  minHeight: 50.0

tablist:
  header: "&4&l&m------&r &c&b&nBreakFFA&r &4&l&m------"
  footer: "&4&l&m----&r &c&b{version} &4&b| &c&b{players} joueurs&r &4&l&m----"

lobbySpawn:
  x: 0.0
  y: 0.0
  z: 0.0

nexusLocation:
  x: 0.0
  y: 0.0
  z: 0.0

spawns:
  - x: 0.0
    y: 0.0
    z: 0.0
    pitch: 0.0
    yaw: 0.0